// Shared course catalog (replace with a real API fetch() when available)
var COURSES = [
  { id:1, title:'Full-Stack Web Development with Python', instructor:'Dr. Anika Perera', category:'Development', level:'Intermediate', duration:'14h', rating:4.8, price:49, lessons:42, students:12430, bestseller:true, grad:['#4F46E5','#2E1F8F'],
    summary:'Build complete web apps from database to UI using Python, Flask, and modern front-end tooling.',
    learn:['Design and build RESTful APIs with Flask','Model and query data with SQLAlchemy','Ship a responsive front end with HTML, CSS & JS','Deploy a full-stack app to production'],
    curriculum:['Course orientation & setup','Working with Flask & routing','Databases & SQLAlchemy models','Building the REST API','Front-end integration','Auth & sessions','Testing & deployment'] },
  { id:2, title:'UX & UI Design Fundamentals', instructor:'Marcus Lee', category:'Design', level:'Beginner', duration:'9h', rating:4.7, price:0, lessons:28, students:8930, bestseller:false, grad:['#0EA5A0','#0B7C78'],
    summary:'Learn the principles behind interfaces people love to use — from research to polished prototypes.',
    learn:['Run lightweight user research','Apply layout, color & type systems','Prototype and test in Figma','Build an accessible component library'],
    curriculum:['What is UX vs UI','User research basics','Visual hierarchy & color','Wireframing','Prototyping in Figma','Accessibility fundamentals','Portfolio review'] },
  { id:3, title:'Data Analysis with Pandas & SQL', instructor:'Prof. Ravi Nair', category:'Data Science', level:'Intermediate', duration:'11h', rating:4.9, price:39, lessons:34, students:15200, bestseller:true, grad:['#F2A93B','#C77E1B'],
    summary:'Turn raw data into clear insight with Pandas, SQL, and reproducible analysis workflows.',
    learn:['Query data efficiently with SQL','Clean & transform with Pandas','Visualize trends clearly','Tell a story with data'],
    curriculum:['SQL refresher','Loading data with Pandas','Cleaning & shaping','Grouping & aggregation','Visualization','A mini analysis project'] },
  { id:4, title:'Foundations of Digital Marketing', instructor:'Sara Fernando', category:'Marketing', level:'Beginner', duration:'7h', rating:4.5, price:0, lessons:22, students:6400, bestseller:false, grad:['#E5484D','#A83034'],
    summary:'A practical intro to channels, funnels, and campaigns that actually convert.',
    learn:['Map a customer journey','Set up paid & organic channels','Measure what matters','Write copy that converts'],
    curriculum:['Marketing landscape','Audience & positioning','Content & SEO','Paid basics','Email & lifecycle','Measuring ROI'] },
  { id:5, title:'Machine Learning in Production', instructor:'Dr. Wei Chen', category:'Data Science', level:'Advanced', duration:'18h', rating:4.9, price:79, lessons:50, students:9800, bestseller:true, grad:['#6A5CF0','#2E1F8F'],
    summary:'Go beyond notebooks: train, evaluate, and serve models reliably at scale.',
    learn:['Engineer reproducible ML pipelines','Evaluate models rigorously','Serve models via APIs','Monitor & retrain in production'],
    curriculum:['ML systems design','Feature engineering','Training pipelines','Evaluation & fairness','Serving with FastAPI','Monitoring & drift'] },
  { id:6, title:'Startup Finance & Fundraising', instructor:'Olivia Grant', category:'Business', level:'Intermediate', duration:'8h', rating:4.6, price:59, lessons:26, students:4100, bestseller:false, grad:['#4F46E5','#0EA5A0'],
    summary:'Understand cap tables, burn, and the fundraising process from first pitch to term sheet.',
    learn:['Read and build a financial model','Understand cap tables & dilution','Prepare an investor pitch','Navigate term sheets'],
    curriculum:['Unit economics','Building a model','Cap tables explained','The pitch deck','Meeting investors','Term sheets'] },
  { id:7, title:'React from Scratch to Advanced', instructor:'Tom Becker', category:'Development', level:'Advanced', duration:'16h', rating:4.8, price:49, lessons:46, students:18750, bestseller:true, grad:['#2E1F8F','#4F46E5'],
    summary:'Master components, hooks, state, and performance with real-world React patterns.',
    learn:['Architect with components & hooks','Manage state effectively','Optimize rendering','Test React apps'],
    curriculum:['JSX & components','Props, state & events','Hooks deep dive','Context & data','Performance','Testing & shipping'] },
  { id:8, title:'Brand Identity & Visual Systems', instructor:'Nina Costa', category:'Design', level:'Intermediate', duration:'10h', rating:4.7, price:0, lessons:30, students:5200, bestseller:false, grad:['#0EA5A0','#4F46E5'],
    summary:'Create cohesive brand systems — logos, type, color, and guidelines that scale.',
    learn:['Develop a brand strategy','Design logo systems','Build a type & color system','Write brand guidelines'],
    curriculum:['Brand strategy','Logo construction','Type & color','Application mockups','Guidelines doc'] },
  { id:9, title:'Product Management Essentials', instructor:'James Oduya', category:'Business', level:'Beginner', duration:'6h', rating:4.4, price:29, lessons:20, students:3300, bestseller:false, grad:['#F2A93B','#4F46E5'],
    summary:'Ship products users want with discovery, roadmaps, and clear prioritization.',
    learn:['Run product discovery','Write strong specs','Prioritize with frameworks','Work with eng & design'],
    curriculum:['PM role','Discovery','Roadmaps','Prioritization','Specs & handoff','Metrics'] },
  { id:10, title:'SEO & Growth Analytics', instructor:'Priya Menon', category:'Marketing', level:'Intermediate', duration:'9h', rating:4.6, price:0, lessons:24, students:7600, bestseller:false, grad:['#E5484D','#F2A93B'],
    summary:'Grow organic traffic and measure it with modern SEO and analytics practice.',
    learn:['Audit technical SEO','Build a content strategy','Set up analytics & events','Report on growth'],
    curriculum:['SEO fundamentals','Technical audit','Content strategy','Analytics setup','Reporting'] },
  { id:11, title:'Deep Learning with PyTorch', instructor:'Dr. Anika Perera', category:'Data Science', level:'Advanced', duration:'20h', rating:4.9, price:89, lessons:54, students:11200, bestseller:true, grad:['#2E1F8F','#6A5CF0'],
    summary:'Build, train, and tune neural networks for vision and language with PyTorch.',
    learn:['Build models in PyTorch','Train CNNs & transformers','Tune & regularize','Ship an inference service'],
    curriculum:['Tensors & autograd','Neural network basics','CNNs for vision','Transformers','Training at scale','Serving models'] },
  { id:12, title:'Accessible Front-End Engineering', instructor:'Marcus Lee', category:'Development', level:'Beginner', duration:'8h', rating:4.5, price:0, lessons:23, students:2900, bestseller:false, grad:['#0EA5A0','#2E1F8F'],
    summary:'Engineer interfaces everyone can use, meeting WCAG with semantic, robust markup.',
    learn:['Apply WCAG principles','Build with semantic HTML','Manage focus & ARIA','Test with assistive tech'],
    curriculum:['Why accessibility','Semantics & ARIA','Keyboard & focus','Color & contrast','Testing tools'] }
];
